bugcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('bugs/', views.bugs_index, name='index'),
    path('bugs/<int:bug_id>/', views.bugs_detail, name='detail'),
    path('bugs/create/', views.BugCreate.as_view(), name='bugs_create'),
    path('bugs/<int:pk>/update/', views.BugUpdate.as_view(), name='bugs_update'),
    path('bugs/<int:pk>/delete/', views.BugDelete.as_view(), name='bugs_delete'),
    path('bugs/<int:bug_id>/add_treatment/', views.add_treatment, name='add_treatment'),
    path('bugs/<int:bug_id>/add_photo/', views.add_photo, name='add_photo'),
    path('bugs/<int:bug_id>/assoc_agent/<int:agent_id>/', views.assoc_agent, name='assoc_agent'),
    path('bugs/<int:bug_id>/unassoc_agent/<int:agent_id>/', views.unassoc_agent, name='unassoc_agent'),
    path('agents/', views.AgentList.as_view(), name='agents_index'),
    path('agents/<int:pk>/', views.AgentDetail.as_view(), name='agents_detail'),
    path('agents/create/', views.AgentCreate.as_view(), name='agents_create'),
    path('agents/<int:pk>/update/', views.AgentUpdate.as_view(), name='agents_update'),
    path('agents/<int:pk>/delete/', views.AgentDelete.as_view(), name='agents_delete'),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

PROCEDURES = (
    ('E', 'Extermination'),
    ('F', 'Feeding'),
    ('R', 'Reproduction')
)

class Agent(models.Model):
  name = models.CharField(max_length=50)
  usage = models.CharField(max_length=20)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('agents_detail', kwargs={'pk': self.id})

class Bug(models.Model):
    name = models.CharField(max_length=100)
    latin_name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    lifespan = models.TextField(max_length=250)
    agents = models.ManyToManyField(Agent)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'bug_id': self.id})

class Photo(models.Model):
    url = models.CharField(max_length=200)
    bug = models.ForeignKey(Bug, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for bug_id: {self.bug_id} @{self.url}"

class Treatment(models.Model):
    date = models.DateField()
    procedure = models.CharField(
        max_length=1,
        choices=PROCEDURES,
        default=PROCEDURES[0][0]
    )

    bug = models.ForeignKey(Bug, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_procedure_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Treatment

class TreatmentForm(ModelForm):
  class Meta:
    model = Treatment
    fields = ['date', 'procedure']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import Bug, Agent, Photo
from .forms import TreatmentForm
import uuid
import boto3
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'collectorforme'

# class Bug:
#   def __init__(self, name, latin_name, description, lifespan):
#     self.name = name
#     self.latin_name = latin_name
#     self.description = description
#     self.lifespan = lifespan

# bugs = [
#   Bug('Honey Bee', 'Apis mellifera', 'Bees are winged insects closely related to wasps and ants.', '30-60 days'),
#   Bug('Ant', 'Formicidae', 'Ants form colonies that range in size', '4 years'),
#   Bug('Mosquito', 'Culicidae', 'The word "mosquito" is Spanish and Portuguese for "little fly"', '42-56 days')
# ]

@login_required
def add_photo(request, bug_id):
  photo_file = request.FILES.get('photo-file', None)
  if photo_file:
    s3 = boto3.client('s3')
    key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
    try:
      s3.upload_fileobj(photo_file, BUCKET, key)
      url = f"{S3_BASE_URL}{BUCKET}/{key}"
      photo = Photo(url=url, bug_id=bug_id)
      photo.save()
    except:
      print('An error occurred uploading file to S3')
  return redirect('detail', bug_id=bug_id)

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def bugs_index(request):
  bugs = Bug.objects.filter(user=request.user)
  return render(request, 'bugs/index.html', { 'bugs': bugs })

@login_required
def bugs_detail(request, bug_id):
  bug = Bug.objects.get(id=bug_id)
  agents_bug_doesnt_have = Agent.objects.exclude(id__in = bug.agents.all().values_list('id'))
  treatment_form = TreatmentForm()
  return render(request, 'bugs/detail.html', {
    'bug': bug, 'treatment_form': treatment_form,
    'agents': agents_bug_doesnt_have
  })

@login_required
def add_treatment(request, bug_id):
  form = TreatmentForm(request.POST)
  if form.is_valid():
    new_treatment = form.save(commit=False)
    new_treatment.bug_id = bug_id
    new_treatment.save()
  return redirect('detail', bug_id=bug_id)

@login_required
def assoc_agent(request, bug_id, agent_id):
  Bug.objects.get(id=bug_id).agents.add(agent_id)
  return redirect('detail', bug_id=bug_id)

@login_required
def unassoc_agent(request, bug_id, agent_id):
  Bug.objects.get(id=bug_id).agents.remove(agent_id)
  return redirect('detail', bug_id=bug_id)

class BugCreate(LoginRequiredMixin, CreateView):
  model = Bug
  fields = '__all__'
  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)

class BugUpdate(LoginRequiredMixin, UpdateView):
  model = Bug
  fields = ['latin_name', 'description', 'lifespan']

class BugDelete(LoginRequiredMixin, DeleteView):
  model = Bug
  success_url = '/agents/'

class AgentList(LoginRequiredMixin, ListView):
  model = Agent

class AgentDetail(LoginRequiredMixin, DetailView):
  model = Agent

class AgentCreate(LoginRequiredMixin, CreateView):
  model = Agent
  fields = '__all__'

class AgentUpdate(LoginRequiredMixin, UpdateView):
  model = Agent
  fields = ['name', 'usage']

class AgentDelete(LoginRequiredMixin, DeleteView):
  model = Agent
  success_url = '/agents/'

def agent_index(request):
  agents = Agent.objects.all()
  return render(request, 'main_app/agent_list.html', { 'agents': agents })

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Bug Collector</h1>
<hr />
<p>Hire the Bug Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Bug Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Bug Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'agents_create' %}">Add An Agent</a></li>
          <li><a href="{% url 'agents_index' %}">View All Agents</a></li>
          <li><a href="{% url 'bugs_create' %}">Add A Bug</a></li>
          <li><a href="{% url 'index' %}">View All Bugs</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
        {% else %}
        <li><a href="{% url 'signup' %}">Sign Up</a></li>
        <li><a href="{% url 'login' %}">Log In</a></li>
        {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2022 Bug Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/bugs/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Bug Details</h1>

<div class="row">
<div class="col s6">
<div class="card">
  <div class="card-content">
    <span class="card-title">{{ bug.name }}</span>
    <p>Latin Name: {{ bug.latin_name }}</p>
    <p>Description: {{ bug.description }}</p>
    <p>Lifespan: {{ bug.lifespan }}</p>
  </div>
  <div class="card-action">
    <a href="{% url 'bugs_update' bug.id %}">Edit</a>
    <a href="{% url 'bugs_delete' bug.id %}">Delete</a>
  </div>
</div>
{% for photo in bug.photo_set.all %}
      <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
      <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' bug.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <br><br>
      <input type="submit" class="btn" value="Upload Photo">
  </form>
</div>
<div class="col s6">
  <form action="{% url 'add_treatment' bug.id %}" method="post">
    {% csrf_token %} {{ treatment_form.as_p }}
    <input type="submit" class="btn" value="Add Treatment"/>
  </form>
  <table class="striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Treatment</th>
      </tr>
    </thead>
    <tbody>
      {% for treatment in bug.treatment_set.all %}
      <tr>
        <td>{{treatment.date}}</td>
        <td>{{treatment.get_procedure_display}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>Agents for {{ bug.name }}'s</h3>
    {% if bug.agents.count %}
      {% for agent in bug.agents.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A {{ agent.name }} for <span>{{ agent.usage }}</span> 
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'unassoc_agent' bug.id agent.id %}" method="post">
                {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Agents Used</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Agents</h3>
    {% if agents.count %}
      {% for agent in agents.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A {{ agent.name }} for <span>{{ agent.usage }}</span> 
            </span>
          </div>
          <div class="card-action">
            <form action="{% url 'assoc_agent' bug.id agent.id %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{bug.name}} Already Has All Agents Available</h5>
    {% endif %}
  </div>
</div>
<script>
  let dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  let selectEl = document.getElementById('id_procedure');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/bugs/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Bug List</h1>

{% for bug in bugs %}
  <div class="card">
    <a href="{% url 'detail' bug.id %}">
    <div class="card-content">
      <span class="card-title">{{ bug.name }}</span>
      <p>Latin Name: {{ bug.latin_name }}</p>
      <p>Description: {{ bug.description }}</p>
      <p>Lifespan: {{ bug.lifespan }}</p>
    </div>
    </a>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}
<h1>Home</h1>
{% endblock %}

main_app/templates/main_app/agent_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Agent</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'agents_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/agent_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Agent Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ agent.name }}</span>
        <p>Usage: {{ agent.usage}}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'agents_update' agent.id %}">Edit</a>
        <a href="{% url 'agents_delete' agent.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/agent_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Agent</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/agent_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Agent List</h1>

{% for agent in agent_list %}
  <a href="{% url 'agents_detail' agent.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ agent.name }}</span>
            <p>Usage: {{ agent.usage }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/bug_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Bug</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' bug.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/bug_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Bug</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}